server:
  port: 8083
spring:
  application:
    name: search-service # search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.58.132:9300
  rabbitmq:
    host: 192.168.58.132
  main:
    allow-bean-definition-overriding: true  #调用多个feign客户端时需要开启配置，否则不能调用报错
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:  #设置心跳反应时间  在注册服务完成以后，服务提供者会维持一个心跳（定时向EurekaServer发起Rest请求）,告诉EurekaServer我还活着
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5