server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 1234


    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
  rabbitmq:
    host: 192.168.58.132
  redis:
    host: 192.168.58.132
    port: 6379
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
mybatis:
  type-aliases-package: com.leyou.dao
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
